### ISSUE TITLE
Unable to run unbound custom conf files and port

### ISSUE THREAD

**Issue by SimonInOps** [klutchell/unbound-docker#221]
### Overview
Hi
I'm struggling to change server settings and still not sure what's happening.
According to your [documentation ](https://github.com/klutchell/unbound-docker/tree/v1.18.0#usageexamples), i should be able to mount my custom conf files into `/etc/unbound/custom.conf.d` directory, which should [override](https://github.com/klutchell/unbound-docker/blob/v1.18.0/rootfs_overlay/etc/unbound/unbound.conf#L149) default server settings. But the current behavior looks like it's not working - simply tried to change port and i don't get the answer.
#### 1. Run container without any change
<details>
<summary>File definition</summary>
docker-compose.yml

```
unbound:
    container_name: unbound
    image: klutchell/unbound
    command: "-d -vv"
```

</details> 

<details>
<summary>Testing unbound server</summary>

Like mentioned in a [Readme](https://github.com/klutchell/unbound-docker/tree/v1.18.0#test) section

`docker exec unbound dig @127.0.0.1 dnssec.works`
1st. attempt return result
```
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 51331
;; flags: qr rd ra ; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;; dnssec.works.        IN      A

;; ANSWER SECTION:
dnssec.works.   3600    IN      A      [ip-address]

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 323 msec
;; SERVER: 127.0.0.1
;; WHEN: Tue Oct 31 15:58:38 2023
;; MSG SIZE  rcvd: 46
```

`docker exec unbound dig @127.0.0.1 fail01.dnssec.works`
1st. attempt return
```
Error: error sending query: Could not send or receive, because of network error
```
2nd. attempt return
```
;; ->>HEADER<<- opcode: QUERY, rcode: SERVFAIL, id: 47185
;; flags: qr rd ra ; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;; fail01.dnssec.works. IN      A

;; ANSWER SECTION:

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 0 msec
;; SERVER: 127.0.0.1
;; WHEN: Tue Oct 31 16:29:18 2023
;; MSG SIZE  rcvd: 37
```

Believe everything works as expected
</details> 

#### 2. Mount my custom configuration into container
<details>
<summary>Files definition</summary>
docker-compose.yml

```
unbound:
    container_name: unbound
    image: klutchell/unbound
    command: "-d -vv"
    volumes:
      - "./unbound_conf:/etc/unbound/custom.conf.d"
```
./unbound_conf/unbound2.conf
```
server:
    port: 5353
```
This should override port only
</details> 

<details>
<summary>Testing custom unbound server</summary>

Like mentioned in a [Readme](https://github.com/klutchell/unbound-docker/tree/v1.18.0#test) section

Changed port so testing with `-p 5353` flag
`docker exec unbound dig @127.0.0.1 -p 5353 dnssec.works`
1st./2nd./3rd. attempt return result
```
Error: error sending query: Could not send or receive, because of network error
```

`docker exec unbound dig @127.0.0.1 -p 5353 fail01.dnssec.works`
1st./2nd./3rd. attempt return result
```
Error: error sending query: Could not send or receive, because of network error
```

Also checked default port(just in case), but the result is the same
`docker exec unbound dig @127.0.0.1 dnssec.works`
1st./2nd./3rd. attempt return result
```
Error: error sending query: Could not send or receive, because of network error
```

`docker exec unbound dig @127.0.0.1 fail01.dnssec.works`
1st./2nd./3rd. attempt return result
```
Error: error sending query: Could not send or receive, because of network error
```

</details> 

No logs appear in the docker logs like it used to be with the default configuration.
Permissions are correct - 101:102

Tried also:

- Copy and paste whole [unbound.conf](https://github.com/klutchell/unbound-docker/blob/v1.18.0/rootfs_overlay/etc/unbound/unbound.conf) into `custom.conf` directory, change port and comment `auto-trust-anchor-file` setting (because container complains when have doubled this setting) - no effect
- Set custom command and point a config file - dig still can't communicate
- Use minimal config from an [unbound website](https://unbound.docs.nlnetlabs.nl/en/latest/manpages/unbound.conf.html#example), add custom port - no response, no docker logs

What am i missing? What's wrong and how to make custom config works?
Thank you

**Comment by klutchell** [comment]
Can you share the exact content of the custom config files you tried?

For example, when you copied the example `unbound.conf` into `custom.conf.d` did you remove the `include-toplevel` line to avoid recursive imports?

What if you provide a config file that has only the port in it?

```
# /etc/unbound/custom.conf.d/custom-port.conf
server:
    port: 5353
```

**Comment by SimonInOps** [comment]
> Can you share the exact content of the custom config files you tried?
> 
> For example, when you copied the example `unbound.conf` into `custom.conf.d` did you remove the `include-toplevel` line to avoid recursive imports?
> 
> What if you provide a config file that has only the port in it?
> 
> ```
> # /etc/unbound/custom.conf.d/custom-port.conf
> server:
>     port: 5353
> ```

Maybe i shouldn't use this "hidden details" feature, but already posted files' content :)
<img width="401" alt="Screenshot" src="https://github.com/klutchell/unbound-docker/assets/48860550/fafe64ec-ad3d-457e-892c-c18bfbb6e358">
When i only define port nothing changes as described above. 
Only update to this, when i ask docker dns (127.0.0.11) i receive response. So far no idea what is the reason. Maybe a docker issue 🤔

**Comment by klmcwhirter** [comment]
+1 on resolving this issue.

I need this feature (I think - based on research so far) to use unbound as a resolver for pihole with dhcp enabled on Raspberry Pi 4. It seems that I need to use network_mode: host in docker-compose.yml. Obviating the need for a port other than 53 for unbound.

Note I have it all working without DHCP enabled, custom network config (instead of network_mode: host) and port mapping to 5353.

Admittedly, I am early in the process ... but, @Drozdzufka is that what you are attempting as well?

@klutchell have you encountered this use case before? Am I heading in the right direction?

Thanks for your work both of you!

**Comment by klutchell** [comment]
Until very recently I was using a similar setup, providing a custom config file to change the port assignment without issues.
https://github.com/klutchell/balena-pihole/tree/894830c3672f567df3901a86dcc00deb552380e1/unbound/custom.conf.d

Based on the above I know configuration overrides are working, including changing the port. This repo also has [automated tests that mount an example custom conf file](https://github.com/klutchell/unbound-docker/blob/1235a3614dfbb03d649c0272f21dcd5d4cb0f646/docker-compose.test.yml#L10-L13) at runtime.

> No logs appear in the docker logs like it used to be with the default configuration.

I think we should focus on this note from your original message. I suspect there is an issue with the mounting of the file via docker-compose, and not the contents of the file specifically. I will try to reproduce when I have the chance.

In the meantime do you want to try building a dockerfile with the following lines and see if the behaviour changes?
```Dockerfile
FROM klutchell/unbound:v1.19.0

COPY custom.conf.d/*.conf /etc/unbound/custom.conf.d/
```

Can you also check that you have pulled the latest unbound image v1.18.0 or v1.19.0 at least?

**Comment by klutchell** [comment]
I reproduced the issue and it works when using `interface` instead of `port`.

```
server:
    interface: 0.0.0.0@5353
```

The [documentation](https://unbound.docs.nlnetlabs.nl/en/latest/manpages/unbound.conf.html) isn't clear why this is. Perhaps because `port` is just a default setting it cannot be overridden the same way other properties can?

Or maybe because the default config already specifies `interface: 0.0.0.0` and the `@53` is implied by the existing value of `port: 53` before any overrides even get loaded.

To test the above I tried the following but got an error:
```
server:
    port: 5353
    interface: 0.0.0.0
```
```
unbound-checkconf[13:0] fatal error: interface: 0.0.0.0 present twice, cannot bind same ports twice.
```
So it seems that interface without a port can only be specified once because there is some implied port that we cannot see, which means it isn't using the value for `port:` in the way I was thinking.

I think the correct way forward is to remove the `port: 53` definition from the default config and just use `interface: 0.0.0.0@53` and custom configs can add to the list of interfaces (but not remove any unfortunately). At least that way it's clear what is being used and what is required in a custom config override.

**Comment by klutchell** [comment]
In addition to the above, we will also need to make it easier to replace the default config file in cases where appending to the listen interfaces is not enough, and we need to remove the default to avoid conflicts. The override system is not suitable for that.

**Comment by klmcwhirter** [comment]
@klutchell thanks for letting me tag along for the troubleshooting process here. You guys really did help me think some things through.

For what it is worth I think I am going to head down the path of a single container with both pihole and unbound to avoid the need for the macvlan approach and give me greater control on how unbound is used by pihole via loopback.

Regardless, here is an example unbound config that shows, I believe, exactly what you were describing. I hope this will give you another data point.

[chriscrowe one-container unbound.conf using both interface and port items](https://github.com/chriscrowe/docker-pihole-unbound/blob/main/one-container/pihole-unbound/unbound-pihole.conf#L8)

_Note I am not completely convinced on the details of this example. For example, I like your distro-less approach. If I am going to use network_mode: host to enable DHCP what is the point of a complete debian installation, etc._

For completeness, I also hope to use the resulting config in 2 different instances of OMV6 for pseudo-HA and also [gravity-sync](https://github.com/vmstan/gravity-sync) for one-way replication to the secondary. Wish me luck ;)

If you don't mind, I'll continue to watch your progress.

Thanks again.

**Comment by SimonInOps** [comment]
@klmcwhirter Not exactly. Playing with config options.
btw. You can use bridge network with defined ipam for pihole and unbound(static ip). Then you don't have to expose port from unbound container - docker communicate inside, so setting this static ip as a dns in pihole will work

@klutchell 
> I reproduced the issue and it works when using `interface` instead of `port`.
> 
> ```
> server:
>     interface: 0.0.0.0@5353
> ```
> 
> The [documentation](https://unbound.docs.nlnetlabs.nl/en/latest/manpages/unbound.conf.html) isn't clear why this is. Perhaps because `port` is just a default setting it cannot be overridden the same way other properties can?

Yeah! Confirming this setting works! Documentation also says - when port is not specified in the "interface" option, should be taken from "port" setting, so anyway should have worked i think.

> if not specified the default port (from [port:](https://unbound.docs.nlnetlabs.nl/en/latest/manpages/unbound.conf.html#unbound-conf-port)) is used

Tested the wrong config on my side

> To test the above I tried the following but got an error:
server:
    port: 5353
    interface: 0.0.0.0

I don't get the error - container startup normally, dig does not work.
Copied whole unbound.conf from this repository, changed port in interface, removed port option, mounted under `/etc/unbound/unbound.conf`. Starts normally, no errors, dig NOT working 🤯. Like some settings cause some conflict maybe...

**Comment by klutchell** [comment]
@Drozdzufka note that `dig` is not a binary in the unbound container image, you need to use `drill` instead. This changed a couple releases ago I think.

Dig should still work for testing from outside the container like we do as part of automated testing.

**Comment by SimonInOps** [comment]
Okay, checked what's inside latest Release 1.19
https://github.com/klutchell/unbound-docker/blob/v1.19.0/Dockerfile#L54

> ln -s drill /opt/usr/bin/dig
...
RUN [ "drill", "-v" ]
RUN [ "dig", "-v" ]

Both commands works for me similar when i do `docker exec` and results are the same

**Comment by klutchell** [comment]
> Okay, checked what's inside latest Release 1.19 https://github.com/klutchell/unbound-docker/blob/v1.19.0/Dockerfile#L54
> 
> > ln -s drill /opt/usr/bin/dig
> > ...
> > RUN [ "drill", "-v" ]
> > RUN [ "dig", "-v" ]
> 
> Both commands works for me similar when i do `docker exec` and results are the same

Right, I forgot that [I added a symlink](https://github.com/klutchell/unbound-docker/blob/e20af414cf23e08c12d6fc2e344575f6bedf25c9/Dockerfile#L51-L54) from dig -> drill for compatibility reasons.

**Comment by klutchell** [comment]
> I don't get the error - container startup normally, dig does not work.
> Copied whole unbound.conf from this repository, changed port in interface, removed port option, mounted under /etc/unbound/unbound.conf. Starts normally, no errors, dig NOT working 🤯. Like some settings cause some conflict maybe...

@Drozdzufka Sorry, but I'm not clear from this message what is or isn't working now. Can you recap your current setup in detail and exactly what is or isn't working for you? Can you also try with the latest `main` tag that includes the last couple merges?

**Comment by klmcwhirter** [comment]
@Drozdzufka the output from `docker log ...` might help vs the output from `docker exec ...`.

BTW, had a very painful night restoring backup of my router multiple times trying to enable DHCP on my pi.hole instances. I am done with that. And am back with you guys ...

I did get it working. But not reliably. When there is an issue - factory reset the router again. Uggh.

I do question this part of the config ...
[https://github.com/klutchell/unbound-docker/blob/main/rootfs_overlay/etc/unbound/unbound.conf#L98-L111](https://github.com/klutchell/unbound-docker/blob/main/rootfs_overlay/etc/unbound/unbound.conf#L98-L111)

Are those CIDRs correct in general? Or are there potential routing issues because of them.

For example. 192.168.0.0/16 vs 192.168.1.0/24 ...

I'll be digging into that next once I get myself back to where I was.

**Comment by klmcwhirter** [comment]
I made a little progress ...

I noticed that the dig command responds to both ports 53 and 5353. So I mounted the entire unbound.conf file with the lines like this:

```
interface: 172.28.0.2
port: 5353
```

I also modified the healthcheck CMD to use @172.28.0.2 - the SAME interface.

That seems to be working - although it is not exactly what we want.

The lesson learned for me is that the interface: directives are additive. Tomorrow, I'll try to specify the following in unbound.conf:
```
interface: 172.28.0.2
port: 53
```
And the following in custom-port.conf to see if it is overridden when the same interface is specified.
```
interface: 172.28.0.2
port: 5353
```
I'll also try the following because the docs suggest that the order might matter.
> A port number can be specified with `@port` (without spaces between interface and port number), if not specified the default port (from [**port:**]) is used.
```
port: 5353
interface: 172.28.0.2
```

I'll report back.

**Comment by klmcwhirter** [comment]
@klutchell , @Drozdzufka , this seems to work. Note the order of port and interface DOES matter in the custom-port.conf file!

snippet from unbound.conf file ...
```
server:
  ...
    interface: 127.0.0.1
    port: 53

...
```

custom-port.conf:
```
server:
    port: 5353
    interface: 172.28.0.2
```
**Results in this**
```
# docker exec dns-unbound-1 dig -p 5353 dnssec.works '@172.28.0.2'
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 39774
;; flags: qr rd ra ; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0 
;; QUESTION SECTION:
;; dnssec.works.	IN	A

;; ANSWER SECTION:
dnssec.works.	3571	IN	A	5.45.107.88

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 0 msec
;; SERVER: 172.28.0.2
;; WHEN: Fri Nov 17 17:03:49 2023
;; MSG SIZE  rcvd: 46
```
Note that these do not resolve:
- `docker exec dns-unbound-1 dig -p 53 dnssec.works '@0.0.0.0'`
- `docker exec dns-unbound-1 dig -p 53 dnssec.works '@127.0.0.1'`

But these do as well as 172.28.0.2:5353:
- `docker exec dns-unbound-1 dig -p 5353 dnssec.works '@0.0.0.0'`
- `docker exec dns-unbound-1 dig -p 5353 dnssec.works '@127.0.0.1'`

To be honest, the unbound.conf is not that large. And because of the additive nature of the config it feels safer to me to just provide the whole file. I do realize that means dealing with change over upgrades - the mapped file will need to be maintained. But, ...

Hope that helps.
[docker-compose.yml.txt](https://github.com/klutchell/unbound-docker/files/13394757/docker-compose.yml.txt)

[EDIT for future reference]
I believe the reason the order is significant in custom-port.conf is because of how the interface config item works according to the docs - i.e., the port _default_ that is in effect at the time the interface item is evaluated is used.
> A port number can be specified with `@port` (without spaces between interface and port number), **if not specified the default port (from [**port:**]) is used.**

Hence, setting port first (5353) causes that to be used when adding the custom interface (172.28.0.2).

**Comment by klutchell** [comment]
Thanks for the additional testing @klmcwhirter !

Has your original issue been resolved @Drozdzufka? Can we close this issue and refer back to it if we are confused about overrides in the future?

**Comment by klmcwhirter** [comment]
@klutchell you are very welcome.

Thank YOU for figuring this stuff out for us.

I love having unbound in an 11.2MiB docker image on my Raspberry Pi ;)

**Comment by SimonInOps** [comment]
Yes, resolved. 
Thank you and Merry Christmas!
Closing
