### ISSUE TITLE
Are the builds tied to a specific kernel version?

### ISSUE THREAD

**Issue by rahul-thakoor** [klutchell/unbound-docker#23]
https://github.com/klutchell/unbound-dnscrypt/blob/130aa4c86962fa85609e965ac5fb285207f94e78/config/common.cfg#L2

hey @klutchell I was wondering what this option does? Does this mean that the resulting rootfs would be tied to a specific kernel version?

I was trying a build based on your Dockerfile here and disabling this option results in an error that kernel is too old :/

Thanks 🙏

**Comment by klutchell** [comment]
Good question, I copied that from here which was written by @jakogut
https://github.com/balena-io-playground/buildroot-base/blob/main/config/common.cfg

It looks to me like it sets the version of the linux-headers kernel package to 4.19 for the toolchain?
https://github.com/buildroot/buildroot/blob/master/package/linux-headers/Config.in.host

I don't think this ties it to a specific kernel version as much as ensures compatibility with baseline kernel features. You could try increasing it to a more recent version of headers if you'd like but I don't think anything is wrong with the current value.

**Comment by rahul-thakoor** [comment]
thanks @klutchell 
I tried looking for more info on that config but couldn't find it 😅

**Comment by jakogut** [comment]
@rahul-thakoor I'm familiar with the purpose of the kernel headers version config, but for reference, I would do `make menuconfig`, navigate to the config in question, and choose `< Help >` (or press H):

>  Select the kernel version to get headers from.                                                                 
>                                                                                                                  
>  The kernel headers must be at least as old as the oldest                                                       
>  kernel you intend to run on your target.    

The underlying reason for this is explained in [this](http://lists.busybox.net/pipermail/buildroot/2012-October/060412.html) archived mailing list thread.

Essentially, the toolchain's libc is built against the kernel headers. If you need a recent kernel feature (system call, etc.), pick the kernel header version that provides that interface. Otherwise, pick the oldest kernel version you intend to run on, as newer versions are backwards compatible.

**Comment by rahul-thakoor** [comment]
thanks for the detective work there @jakogut 👍

**Comment by jakogut** [comment]
@rahul-thakoor Also, I picked this version as it was the oldest LTS commonly (subjectively, in my perception) in use at the time.

**Comment by jakogut** [comment]
This may cause issues if you try to run these images/applications on Jetson devices, which are still shipping v4.9 kernels.
