### ISSUE TITLE
Is the latest tag on dockerhub actually the latest image?

### ISSUE THREAD

**Issue by garlic-hub** [klutchell/unbound-docker#517]
Dockerhub shows `latest` tag as from 3 weeks ago, but looking at the repo tags that seems to correspond to [v1.21.1](https://github.com/klutchell/unbound-docker/releases/tag/v1.21.1) rather than [v1.22.0](https://github.com/klutchell/unbound-docker/releases/tag/v1.22.0).

Tangent to this issue is that the examples folder now uses the drill-hc wrapper, but that doesn't exist unless you pull down the `main` tag on dockerhub.

**Comment by klutchell** [comment]
Good catch, I forgot to tag v1.22.0 as latest. I'll do that now.

**Comment by klutchell** [comment]
The `latest` tag should align to `v1.22.0` now, and as a bonus it includes the drill-hc changes. We can close this if it looks good on your end.

**Comment by garlic-hub** [comment]
Works on my system. I will say it feels a bit chaotic to delete a week old tag and replace it :laughing:. Maybe a minor version bump next time.

**Comment by klutchell** [comment]
Agreed, not something I would do at my day job to be sure.

I don't currently have any revision/build tagging set up for this repo, just branch names or the upstream Unbound version. I figured in this case since none of the v1.22.0 images had actually successfully published anywhere, I could get away with some repo tagging infractions.
